stages:
  preprocess:
    cmd: python3.11 src/preprocess.py
    deps:
    - data/iris.csv
    outs:
    - data/test.csv
    - data/train.csv
  train:
    cmd: python3.11 src/train.py
    deps:
    - data/train.csv
    outs:
    - models/iris_model.pkl
    metrics:
    - metrics/train.json:
        cache: false
  evaluate:
    cmd: python3.11 src/evaluate.py
    deps:
    - data/test.csv
    - models/iris_model.pkl